---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  releaseName: promtail
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana-promtail
        namespace: monitoring
      version: "6.8.*"
  interval: 30m0s
  targetNamespace: monitoring
  install:
    remediation:
      retries: 3
  values:
    image:
      registry: docker.io
       # -- Docker image repository
      repository: grafana/promtail

    serviceMonitor:
      enabled: true

    config:
      clients:
        - url: http://loki.monitoring.svc:3100/loki/api/v1/push

    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 50Mi

    rbac:
      pspEnabled: true