---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx-ingress
spec:
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: nginx-ingress
      version: "4.4.*"
  interval: 30m0s
  install:
    remediation:
      retries: 3
  values:
    podSecurityPolicy:
      enabled: true
    controller:
      image:
        registry: registry.k8s.io
        image: ingress-nginx/controller
      admissionWebhooks:
        patch:
          enabled: true
          image:
            registry: registry.k8s.io
            image: ingress-nginx/kube-webhook-certgen
      resources:
        requests:
          memory: 250Mi
          cpu: 250m
        limits:
          memory: 500Mi
          cpu: 500m
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
      setAsDefaultIngress: true
    defaultBackend:
      image:
        registry: registry.k8s.io
        image: defaultbackend-amd64
      enabled: true
      resources:
        requests:
          memory: 50Mi
          cpu: 100m
        limits:
          memory: 100Mi
          cpu: 150m
