---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: sealed-secrets
      version: "2.7.*"
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    crd:
      create: false
    image:
      registry: docker.io
      repository: bitnami/sealed-secrets-controller
    rbac:
      pspEnabled: true
    resources:
      requests:
        memory: 75Mi
        cpu: 75m
      limits:
        memory: 125Mi
        cpu: 250m