---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  releaseName: external-dns
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: external-dns
      version: "6.13.*"
  interval: 30m0s
  install:
    remediation:
      retries: 3
  values:
    image:
      registry: docker.io
      repository: bitnami/external-dns
    rbac:
      pspEnabled: true
    provider: azure
    azure:
      resourceGroup: ""
      tenantId: ""
      subscriptionId: ""
      useManagedIdentityExtension: true
    domainFilters:
      -  "example.de"
    txtOwnerId: external-dns
