{
 "title": "Overview: Detect Overcommitting  Resource Limits  in K8s",
 "tags": [ "detect-overcommitting" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Top 10 Container without CPU limits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,sum by (namespace,pod,container)(rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"cpu\"}))"
    }
   ]
  },
  {
   "title": "Top 10 Container without Memory Limits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "topk(10,sum by (namespace,pod,container)(container_memory_usage_bytes{container!=\"\"}) unless sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"memory\"}))"
    }
   ]
  },
  {
   "title": "Compare Container CPU_Usage vs CPU_Limits",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (namespace,pod,container)(rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) / (sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"cpu\"})) > 0.8"
    }
   ]
  },
  {
   "title": "Compare Container MEMORY_Usage vs MEMORY_Limits",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "(sum by (namespace,pod,container)(container_memory_usage_bytes{container!=\"\"}) / sum by (namespace,pod,container)(kube_pod_container_resource_limits{resource=\"memory\"})) > 0.8"
    }
   ]
  },
  {
   "title": "Conservative Strategy Finding the right CPU Limit [Overcommit <125%]",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "max by (namespace,owner_name,container)((rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[5m])) * on(namespace,pod) group_left(owner_name) avg by (namespace,pod,owner_name)(kube_pod_owner{owner_kind=~\"DaemonSet|StatefulSet|Deployment\"}))"
    }
   ]
  },
  {
   "title": "Conservative Strategy Finding the right Memory Limit  [Overcommit <125%]",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "max by (namespace,owner_name,container)((container_memory_usage_bytes{container!=\"POD\",container!=\"\"}) * on(namespace,pod) group_left(owner_name) avg by (namespace,pod,owner_name)(kube_pod_owner{owner_kind=~\"DaemonSet|StatefulSet|Deployment\"}))"
    }
   ]
  },
  {
   "title": "Detect Overcommitting compared to Nodes-Memory vs Pods-Memory-Limits",
   "type": "gauge",
   "description": "If the value is equal to 1, then the limits are equal to the available resources.\nIf the value is greater than 1, then the limits are greater than the available resources. \nNote: The control planes distort the result because they are included in the calculation. Due to the gain on the control planes, fewer resources are available. \nIf the value is greater than 1, then the limits are greater than the available resources. ",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(kube_pod_container_resource_limits{container!=\"\",resource=\"memory\"} ) / sum(kube_node_status_capacity{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Detect Overcommitting compared to Nodes-CPU vs Pods-CPU-Limits",
   "type": "gauge",
   "description": "If the value is equal to 1, then the limits are equal to the available resources.\nIf the value is greater than 1, then the limits are greater than the available resources. \nNote: The control planes distort the result because they are included in the calculation. Due to the gain on the control planes, fewer resources are available. ",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(kube_pod_container_resource_limits{container!=\"\",resource=\"cpu\"} ) / sum(kube_node_status_capacity{resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "NotReady Nodes in Kubernetes-Cluster",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_labels) - sum(kube_node_status_condition{condition=\"Ready\"})"
    }
   ]
  },
  {
   "title": "Nodes in Kubernetes-Cluster",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (kube_node_labels)" }
   ]
  },
  {
   "title": "Control-Planes in Kubernetes-Cluster",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_role{role=\"master\"})"
    }
   ]
  },
  {
   "title": "Worker-Nodes in Kubernetes-Cluster",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_labels) - sum(kube_node_role{role=\"master\"})"
    }
   ]
  }
 ]
}